InterviewBot/Front/urls.py
from django.urls import path
from Front import views

app_name='Front'

urlpatterns=[
    path('register/',views.register,name="register"),
    path('user_login/',views.user_login,name="user_login"),

]

InterviewBot/InterviewBot/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from Front import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.welcome,name='welcome'),
    path('Front/',include('Front.urls')),
    path('special/',views.special,name="special"),
    path('logout/',views.user_logout,name="logout"),
    path('Interview/<int:count>/<int:pk>/<int:comp_pk>',views.Interview,name='Interview'),
    path('complete/<int:pk>',views.complete,name='complete'),
    path('description/<int:pk>',views.description,name='description'),
    path('result/<int:pk_cp>',views.score,name='result')
]

InterviewBot/templates/Interview.html
{% extends 'basic.html' %}
{% block body_block %}
{% load static %}

<h1 class="bg-success"><center>Interview :<strong> {{company.Company_name}}</strong></center></h1>
<h5 class="bg-warning"><center><strong>For {{company.Position}} Post</strong></center></h5>
<div class="jumbotron">

  <audio autoplay>
  <source src="{% static "" %}{{ file_name }}" type="audio/mpeg">
  Your browser does not support the audio element.
</audio>
  <form method="POST" action="{% url 'Interview' count=c pk=user.pk comp_pk=company.pk %}">
    {% csrf_token %}
    <label for="question">Answer this question {{user.first_name}} !!!</label>
    <br>
    <h3>Question : <strong>{{ questions1 }}</strong></h3>
    <textarea id='btnGiveCommand' name="answer" rows="8" cols="80"></textarea>
    <br>
    <input type="submit" name="" value="Next" class="btn btn-success">



  </form>

<!---<button id='btnGiveCommand' class="btn btn-link">									<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path d="M12 14c1.66 0 2.99-1.34 2.99-3L15 5c0-1.66-1.34-3-3-3S9 3.34 9 5v6c0 1.66 1.34 3 3 3zm5.3-3c0 3-2.54 5.1-5.3 5.1S6.7 14 6.7 11H5c0 3.41 2.72 6.23 6 6.72V21h2v-3.28c3.28-.48 6-3.3 6-6.72h-1.7z"/></svg>								</button>
--->
</div>
<script>
    var message = document.querySelector('#message');
    var SpeechRecognition = SpeechRecognition || webkitSpeechRecognition;
    var SpeechGrammarList = SpeechGrammarList || webkitSpeechGrammarList;
    var grammar = '#JSGF V1.0;'
    var recognition = new SpeechRecognition();
    var speechRecognitionList = new SpeechGrammarList();
    speechRecognitionList.addFromString(grammar, 1);
    recognition.grammars = speechRecognitionList;
    recognition.lang = 'en-US';
    recognition.interimResults = false;
    recognition.onresult = function(event) {
        var last = event.results.length - 1;
        var command = event.results[last][0].transcript;
        btnGiveCommand.textContent = btnGiveCommand.textContent+' '+command;
    };
    recognition.onspeechend = function() {
        recognition.stop();
    };
    recognition.onerror = function(event) {
        message.textContent = 'Error occurred in recognition: ' + event.error;
    }
    document.querySelector('#btnGiveCommand').addEventListener('click', function(){
        recognition.start();
    });
</script>
{% endblock %}

InterviewBot/templates/Login.html
{% extends 'basic.html' %}
{% block body_block %}
<div class="jumbotron">
  <h1>Please Login</h1>
  <form action="{% url 'Front:user_login' %}" method="post">
    {% csrf_token %}
    <label for="username">Username:</label>
    <input type="text" name="username" placeholder="Enter Username here" class="form-control">
    <label for="password">Password:</label>
    <input type="password" name="password" placeholder="Enter Password here" class="form-control">
    <br>
    <input type="submit" name="" value="Login" class="btn btn-primary">
  </form>
</div>
{% endblock %}

InterviewBot/templates/Registration.html
{% extends 'basic.html' %}
{% load staticfiles %}

{% block body_block %}
<div class="jumbotron">
  {% if registered %}
  <h1>Thank you for Registration!</h1>
  <h4>go to login for sign in and for next stage</h4>
  {% else %}
  <h1>Registration Form</h1>
  <h3>Fill out the form:</h3>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <table>
    {{ user_form.as_table }}
    {{ profile_form.as_table }}

    </table>
    <input type="submit" name="" value="Register" class="btn btn-primary">
  </form>
  {% endif %}
</div>
{% endblock %}

InterviewBot/templates/basic.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    {% load static %}
    <title>Interview Bot</title>
    <link rel="shortcut icon" type="image/x-icon" href="static/robo.png" />

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

  </head>

    <nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url 'welcome'%}"><strong>Interview BOT</strong></a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="{% url 'welcome' %}">Welcome </a></li>
        <li><a href="{% url 'Front:register' %}">Registration</a></li>
        <li><a href="{% url 'admin:index' %}">Admin</a></li>
        {% if user.is_authenticated %}
        <li><a href="{% url 'logout' %}">Log Out</a></li>
        {% else %}
        <li><a href="{% url 'Front:user_login' %}">Log In</a></li>
        {% endif %}
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
    <div class="container">
        {% block body_block %}
        {% endblock %}

    </div>
  </body>
</html>

InterviewBot/templates/description.html
{% extends 'basic.html' %}
{% block body_block %}
<style>
table, th, td {
  border-collapse: collapse;
}
th, td {
  padding: 5px;
  text-align: left;
}
</style>
<h1><strong>Job Description:</strong> </h1>
<h4>
<table width="100%" height="300">
  <tr>
    <td><strong>Company Name: </strong></td>
    <td class="text-success">{{company.Company_name}}</td>
  </tr>
<tr>
<td> </td>
</tr>
  <tr>
    <td><strong> Position: </strong></td>
    <td class="text-success"> {{company.Position}} </td>
  </tr>

  <tr>
<td> </td>
<td> </td>
  </tr>
  <tr>
    <td><strong>Salary: </strong></td>
    <td class="text-success"> {{company.salary_in_rupees}} rupees CTC </td>
    </tr>
  <tr>
<td> </td>
<td> </td>
  </tr>
  <tr>
    <td><strong>Experience required:</strong> </td>
    <td class="text-success"> {{company.min_experience_in_years}} years or above </td>
  </tr>
  <tr>
<td> </td>
<td> </td>
  </tr>
  <tr>
    <td> <strong>Description of company: </strong> </td>
    <td class="text-success"> {{company.Discreption}}</td>
  </tr>
  </h4>
</table>
<br>
<a href="{% url 'Interview' count=0 pk=user.pk comp_pk=company.pk %}"  class='btn btn-warning'>Start Interview</a>
<a href="{% url 'welcome' %}" class="btn btn-danger">Back</a>
<a href="{% url 'result' pk_cp=company.pk %}" class="btn btn-success">Results</a>
{% endblock %}

InterviewBot/templates/done.html
{% extends 'basic.html' %}
{% block body_block %}

<center><h1>Successfully Submited !!!</h1>

  <br>
  <center><h3>{{ s }}</h3></center>
  <strong><center><h2>Your Score : {{ marks }}/100</h2></center></strong>


    <br>
<center>
<a href="{% url 'welcome' %}" class="btn btn-primary">Home</a>
&nbsp;
<a href="{% url 'logout' %}">Logout</a>
</center>


{% endblock %}

InterviewBot/templates/score.html
{% extends 'basic.html' %}
{% block body_block %}
<div class="jumbotron">
  <h1>Results,</h1>
  <p>Please, find your reslt in the below section. The cut-off for the section is 75 marks below 75 will not be allowed for the next round.</p>
</div>
<h1><center>Result: <strong> {{company.Company_name}} </strong> </center></h1>
<h5><center>For <strong>  {{company.Position}} Post </strong> </center></h5>
<br>

<table class="table table-striped">
  <th>Candidate Username</th>
  <th>Marks</th>
  <th>Result</th>
  {% for candidate in cm %}
  <tr>
    <td><strong>{{candidate.user_name}}</strong></td>
    <td>{{candidate.cm_marks}}</td>
    {% if candidate.cm_marks >= 75  %}
    <td>Pass</td>
    {% else %}
    <td>Fail</td>
    {% endif %}


  </tr>
  {% endfor %}
</table>


{% endblock %}

InterviewBot/templates/welcome.html
{% extends "basic.html" %}
{% block body_block %}
<div class="jumbotron">
  {% if user.is_authenticated %}
  <h1>Welcome to Interview Bot, {{user.first_name}} {{user.last_name}}.</h1>

  <br>
  <a href="{% url 'Interview' count=0 pk=user.pk comp_pk=1 %}"  class='btn btn-warning'>Start Interview</a>
  {% else %}
  <h1>Welcome to Interview Bot,</h1>
  <p>For sign up and Registration press the Registration button on navigation bar and after completing that step go to Login Page and start your interview and please share your experience with us and your result will be avialable to you soon.</p>
  <br>
  <br>
  <center><h2 style="color:red;">Please Login or Register for using Interview Bot</h2></center>

  {% endif %}
</div>
<p>We welcome you to the interview bot made by Abhishek Som,Sagar Yadav & Aditya Kumar Verma.
  Student of Meerut Institute of engineering & technology
  B.tech Computer Science 4th year
</p>
{% if user.is_authenticated %}
<h3><strong>Jobs:</strong> </h3>
{% for company in cp %}
<h4>In {{ company.Company_name }} for the post of {{ company.Position }}. </h4>
<a href="{% url 'description' pk=company.pk %}"  class='btn btn-primary'>{{company.Company_name}} : {{company.Position}}</a>
{% endfor %}
<br>


{% endif %}
{% endblock %}